import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { InsuranceContract, ContractType, PaymentTerms } from '../../entities/insurance-contract.entity';
import { ProviderStatus } from '../../entities/insurance-provider.entity';

export class InsuranceContractResponseDto {
  @ApiProperty() id!: string;
  @ApiProperty() workspaceId!: string;
  @ApiProperty() contractNumber!: string;
  @ApiProperty() insuranceProviderId!: string;
  @ApiPropertyOptional() schemeId?: string;
  @ApiProperty() contractName!: string;
  @ApiProperty({ enum: ContractType }) contractType!: ContractType;
  @ApiProperty({ enum: ProviderStatus }) status!: ProviderStatus;
  @ApiProperty() startDate!: Date;
  @ApiProperty() endDate!: Date;
  @ApiPropertyOptional() signedDate?: Date;
  @ApiPropertyOptional() signedBy?: string;
  @ApiPropertyOptional() renewalPeriodDays?: number;
  @ApiProperty() autoRenew!: boolean;
  @ApiPropertyOptional() noticeDate?: Date;
  @ApiPropertyOptional() noticePeriodDays?: number;
  @ApiPropertyOptional() description?: string;
  @ApiPropertyOptional() termsAndConditions?: string;
  @ApiPropertyOptional() defaultCoveragePercentage?: number;
  @ApiPropertyOptional() discountPercentage?: number;
  @ApiPropertyOptional() coverageDetails?: any;
  @ApiPropertyOptional() exclusions?: any;
  @ApiPropertyOptional() serviceRates?: any;
  @ApiPropertyOptional() benefitLimits?: any;
  @ApiProperty({ enum: PaymentTerms }) paymentTerms!: PaymentTerms;
  @ApiPropertyOptional() customPaymentDays?: number;
  @ApiPropertyOptional() minimumClaimAmount?: number;
  @ApiPropertyOptional() maximumClaimAmount?: number;
  @ApiPropertyOptional() annualContractValue?: number;
  @ApiPropertyOptional() monthlyCapitationAmount?: number;
  @ApiPropertyOptional() estimatedEnrollees?: number;
  @ApiProperty() requiresPreAuthorization!: boolean;
  @ApiPropertyOptional() preAuthorizationValidityDays?: number;
  @ApiProperty() supportsElectronicClaims!: boolean;
  @ApiPropertyOptional() claimsSubmissionFormat?: string;
  @ApiPropertyOptional() claimsSubmissionEmail?: string;
  @ApiPropertyOptional() claimsSubmissionUrl?: string;
  @ApiPropertyOptional() claimProcessingDays?: number;
  @ApiPropertyOptional() contactPerson?: string;
  @ApiPropertyOptional() contactEmail?: string;
  @ApiPropertyOptional() contactPhone?: string;
  @ApiPropertyOptional() billingContactPerson?: string;
  @ApiPropertyOptional() billingContactEmail?: string;
  @ApiPropertyOptional() billingContactPhone?: string;
  @ApiPropertyOptional() specialProvisions?: string;
  @ApiPropertyOptional() notes?: string;
  @ApiPropertyOptional() createdByUserId?: string;
  @ApiPropertyOptional() approvedBy?: string;
  @ApiPropertyOptional() approvedDate?: Date;
  @ApiPropertyOptional() metadata?: any;
  @ApiProperty() isActive!: boolean;
  @ApiProperty() createdAt!: Date;
  @ApiProperty() updatedAt!: Date;

  static fromEntity(entity: InsuranceContract): InsuranceContractResponseDto {
    const dto = new InsuranceContractResponseDto();
    dto.id                          = entity.id;
    dto.workspaceId                 = entity.workspaceId;
    dto.contractNumber              = entity.contractNumber;
    dto.insuranceProviderId         = entity.insuranceProviderId;
    dto.schemeId                    = entity.schemeId;
    dto.contractName                = entity.contractName;
    dto.contractType                = entity.contractType;
    dto.status                      = entity.status;
    dto.startDate                   = entity.startDate;
    dto.endDate                     = entity.endDate;
    dto.signedDate                  = entity.signedDate;
    dto.signedBy                    = entity.signedBy;
    dto.renewalPeriodDays           = entity.renewalPeriodDays;
    dto.autoRenew                   = entity.autoRenew;
    dto.noticeDate                  = entity.noticeDate;
    dto.noticePeriodDays            = entity.noticePeriodDays;
    dto.description                 = entity.description;
    dto.termsAndConditions          = entity.termsAndConditions;
    dto.defaultCoveragePercentage   = entity.defaultCoveragePercentage != null ? Number(entity.defaultCoveragePercentage) : undefined;
    dto.discountPercentage          = entity.discountPercentage        != null ? Number(entity.discountPercentage)        : undefined;
    dto.coverageDetails             = entity.coverageDetails;
    dto.exclusions                  = entity.exclusions;
    dto.serviceRates                = entity.serviceRates;
    dto.benefitLimits               = entity.benefitLimits;
    dto.paymentTerms                = entity.paymentTerms;
    dto.customPaymentDays           = entity.customPaymentDays;
    dto.minimumClaimAmount          = entity.minimumClaimAmount        != null ? Number(entity.minimumClaimAmount)        : undefined;
    dto.maximumClaimAmount          = entity.maximumClaimAmount        != null ? Number(entity.maximumClaimAmount)        : undefined;
    dto.annualContractValue         = entity.annualContractValue       != null ? Number(entity.annualContractValue)       : undefined;
    dto.monthlyCapitationAmount     = entity.monthlyCapitationAmount   != null ? Number(entity.monthlyCapitationAmount)   : undefined;
    dto.estimatedEnrollees          = entity.estimatedEnrollees;
    dto.requiresPreAuthorization    = entity.requiresPreAuthorization;
    dto.preAuthorizationValidityDays = entity.preAuthorizationValidityDays;
    dto.supportsElectronicClaims    = entity.supportsElectronicClaims;
    dto.claimsSubmissionFormat      = entity.claimsSubmissionFormat;
    dto.claimsSubmissionEmail       = entity.claimsSubmissionEmail;
    dto.claimsSubmissionUrl         = entity.claimsSubmissionUrl;
    dto.claimProcessingDays         = entity.claimProcessingDays;
    dto.contactPerson               = entity.contactPerson;
    dto.contactEmail                = entity.contactEmail;
    dto.contactPhone                = entity.contactPhone;
    dto.billingContactPerson        = entity.billingContactPerson;
    dto.billingContactEmail         = entity.billingContactEmail;
    dto.billingContactPhone         = entity.billingContactPhone;
    dto.specialProvisions           = entity.specialProvisions;
    dto.notes                       = entity.notes;
    dto.createdByUserId             = entity.createdByUserId;
    dto.approvedBy                  = entity.approvedBy;
    dto.approvedDate                = entity.approvedDate;
    dto.metadata                    = entity.metadata;
    dto.isActive                    = entity.isActive;
    dto.createdAt                   = entity.createdAt;
    dto.updatedAt                   = entity.updatedAt;
    return dto;
  }
}
