export const BILLING_DEFAULTS = {
  DUE_DATE_DAYS: 30,
  MAX_PAYMENT_AMOUNT: 100000,
  MAX_ITEMS_PER_BILL: 1000,
  PERFORMANCE_WARNING_THRESHOLD_MS: 1000,
  MAX_BATCH_SIZE: 1000,
};

export const NUMBER_PREFIXES = {
  BILL: 'BILL',
  INVOICE: 'INV',
  PAYMENT: 'PAY',
  RECEIPT: 'RCT',
  CLAIM: 'CLM',
  TRANSACTION: 'TXN',
};

export const APPROVAL_THRESHOLDS = {
  SUPERVISOR: 500,
  MANAGER: 2000,
  DIRECTOR: 10000,
  CFO: 50000,
};

export const RETURN_POLICY = {
  DEFAULT_RETURN_WINDOW_DAYS: 30,
  MAX_RETURN_WINDOW_DAYS: 90,
  DEFAULT_RESTOCKING_FEE_PERCENTAGE: 10,
  MAX_RESTOCKING_FEE_PERCENTAGE: 50,
};

export const SERVICE_CATEGORIES: Record<string, { maxPerDay: number; requiresAuth: boolean }> = {
  CONSULTATION: { maxPerDay: 5, requiresAuth: false },
  PROCEDURE: { maxPerDay: 10, requiresAuth: true },
  DIAGNOSTIC: { maxPerDay: 20, requiresAuth: false },
  THERAPY: { maxPerDay: 3, requiresAuth: true },
  EMERGENCY: { maxPerDay: 999, requiresAuth: false },
};

export const BILL_STATUS_TRANSITIONS: Record<string, string[]> = {
  DRAFT: ['PENDING', 'CANCELLED', 'VOIDED'],
  PENDING: ['PARTIAL', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', 'VOIDED'],
  PARTIAL: ['PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED'],
  PARTIALLY_PAID: ['PAID', 'OVERDUE', 'CANCELLED'],
  PAID: ['REFUNDED', 'VOIDED'],
  OVERDUE: ['PARTIALLY_PAID', 'PAID', 'CANCELLED'],
  CANCELLED: [],
  REFUNDED: [],
  VOIDED: [],
};

export const INSURANCE_COVERAGE_RATES: Record<string, number> = {
  CONSULTATION: 0.80,
  PROCEDURE: 0.70,
  DIAGNOSTIC: 0.90,
  THERAPY: 0.60,
  EMERGENCY: 0.85,
  MEDICATION: 0.75,
  CONSUMABLE: 0.50,
};

export const BILLING_ERROR_CODES = {
  BILL_NOT_FOUND: 'BILL_NOT_FOUND',
  BILL_ALREADY_PAID: 'BILL_ALREADY_PAID',
  BILL_CANCELLED: 'BILL_CANCELLED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  PAYMENT_EXCEEDS_BALANCE: 'PAYMENT_EXCEEDS_BALANCE',
  INVALID_PAYMENT_METHOD: 'INVALID_PAYMENT_METHOD',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  BATCH_EXPIRED: 'BATCH_EXPIRED',
  INSURANCE_NOT_ACTIVE: 'INSURANCE_NOT_ACTIVE',
  CLAIM_ALREADY_EXISTS: 'CLAIM_ALREADY_EXISTS',
  DISCOUNT_EXPIRED: 'DISCOUNT_EXPIRED',
  DISCOUNT_USAGE_EXCEEDED: 'DISCOUNT_USAGE_EXCEEDED',
  TAX_NOT_APPLICABLE: 'TAX_NOT_APPLICABLE',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  RETURN_WINDOW_EXPIRED: 'RETURN_WINDOW_EXPIRED',
};
